config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show] do 
    collection do 
      get "attendance"
    end 
    resources :leafs, except: [:index, :show]
    resources :attendances, only: [:new, :create]
  end 
  resources :departments
  resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy] do 
    resources :columns, only: [:new, :create, :destroy, :edit, :update] do 
      patch "update_color"
      resources :cards, only: [:new, :create, :edit, :update, :destroy]
    end 
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "departments#index"
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :project
    has_many :cards, dependent: :destroy
    enum :color, %w[gray zinc stone rose yellow orange green cyan purple].index_by(&:itself), suffix: true, default: :blue

    scope :ordered, -> { order(created_at: :asc)}
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_project, only: %i[new create update_color edit]
  
  def new
    @column = Column.new 
  end

  def create
    @column = @project.columns.build(columns_params)
    respond_to do |format|
      if @column.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append(@project, partial: "columns/column", locals: { column: @column })
          ]
        end
      end
    end 
  end 

  def edit
    @column = Column.find(params[:id])
  end

  def update
    @column = Column.find(params[:id])
    respond_to do |format|
      if @column.update(columns_params)
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(@column, partial: "columns/column", locals: { column: @column })
          ]
        end
      end
    end 
  end 

  def destroy
    @column = Column.find(params[:id])
    @column.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@column)
        ]
      end 
    end 
  end 

  def update_color
    @column = Column.find(params[:column_id])
    respond_to do |format|
      if @column.update(color: params[:color])
        format.turbo_stream do 
          render turbo_stream: [
            turbo_stream.replace(@column, partial: "columns/column", locals: { column: @column })
          ]
        end
      end
    end
  end 

  private 

  def columns_params
    params.require(:column).permit(:name, :description, :color) 
  end

  def set_project
    @project = Project.find(params[:project_id]) 
  end 
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/columns/_column.html.erb
<%= turbo_frame_tag dom_id(column), class: "#{column.color} p-2 min-w-72 w-72 border border-gray-200 rounded-sm shadow-md flex flex-col gap-2 self-start" do %>
    <div class="grid grid-cols-[1fr,auto] items-start gap-2 mb-2">
        <div class="flex flex-col truncate hover:text-clip">
            <p class="font-bold text-black text-md"><%= column.name %> 
                <%= turbo_frame_tag "card_count_#{column.id}" do %>(<%= column.cards.count %>) <% end %>
            </p>
            <p class="text-gray-600 text-base"><%= column.description %> </p>
        </div>
        <div class="flex items-center space-x-1">      
            <div class="rounded-full w-8 h-8 flex text-black items-center justify-center cursor-pointer" data-popover-target="<%= column.id %>_popover_click" data-popover-trigger="click" data-popover-placement="bottom">
                <svg xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" viewBox="0 0 16 16" class="text-black"><path fill="currentColor" d="M9.5 13a1.5 1.5 0 1 1-3 0a1.5 1.5 0 0 1 3 0m0-5a1.5 1.5 0 1 1-3 0a1.5 1.5 0 0 1 3 0m0-5a1.5 1.5 0 1 1-3 0a1.5 1.5 0 0 1 3 0"/></svg>
            </div>
            <div class="absolute z-10 invisible inline-block w-64 text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 p-4" data-popover id="<%= column.id %>_popover_click" role="tooltip">
                <div class="flex flex-col">
                    <p class="font-bold text-black text-md"><%= column.name %></p>
                    <p class="text-gray-600 text-base"><%= column.description %></p>
                </div>
                <hr class="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700">
                <%= link_to "Edit column", edit_project_column_path(column.project, column), data: { turbo_frame: :remote_modal }, class: "cursor-pointer font-medium text-black text-md py-1" %>
                <hr class="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700">
                <%= link_to "Add new card", new_project_column_card_path(column.project, column), data: { turbo_frame: :remote_modal }, class: "cursor-pointer font-medium text-black text-md py-1" %>
                <hr class="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700">
                <p class="font-bold text-black text-md">Change color</p>
                <%= form_with url: project_column_update_color_path(column.project, column), method: :patch, data: { controller: "radio", action: "change->radio#submit" }, class: "flex flex-wrap items-center gap-1" do |form|%>
                    <% Column.colors.keys.each do |color|%>
                        <label>
                            <%= form.radio_button :color, color, { checked: color == column.color, class: "hidden" } %>
                            <span class="<%= color %> rounded-full w-8 h-8 border border-gray-200 block cursor-pointer flex items-center justify-center">
                                <% if color == column.color %>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="2em" class="text-gray-700 block" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7L10 17l-5-5"/></svg>
                                <% end %>
                            </span>
                        </label>
                    <% end %>
                <% end %>
                <hr class="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700">
                <%= button_to "Destroy", project_column_path(column.project, column), method: :delete, class: "py-1 px-4 border border-red-600 bg-red-600 text-sm sm:text-md text-white rounded-md font-inter font-medium cursor-pointer" %>
                <div data-popper-arrow></div>
            </div>
        </div>
    </div>
    <%= turbo_frame_tag "#{column.id}_cards", class: "grid grid-cols-1 gap-2" do %>
        <% column.cards.ordered.each do |card| %>
            <%= render card %>
        <% end %>
    <% end %>
    <%= turbo_frame_tag Card.new do %>
        <%= link_to "New Card", new_project_column_card_path(column.project, column), class: "" %>
    <% end %>
<% end %>

app/views/columns/_form.html.erb
<%= form_with(model: [project, column], class: "flex flex-col space-y-2") do |form| %>
    <div class="my-2">
        <%= form.text_field :name, placeholder: "Name", class: "p-2 w-full border border-gray-200 rounded-md" %>
    </div>
    <div class="my-2">
        <%= form.text_area :description, placeholder: "Description", class: "p-2 w-full border border-gray-200 rounded-md" %>
    </div>
    <div class="my-2">
        <%= form.select :color, Column.colors.to_a, class: "p-2 w-full border border-gray-200 rounded-md" %>
    </div>
    <div class="my-2 flex items-center space-x-2">
        <%= form.submit "Save", data: { action: "click->modal#close" }, class: "py-1 px-4 border border-emerald-600 bg-emerald-600 text-sm sm:text-md text-white rounded-md font-inter font-medium cursor-pointer"%>
        <%= form.button "Close", value: nil, formmethod: :dialog, class: "py-1 px-4 border border-emerald-600 text-emerald-600 text-sm sm:text-md rounded-md font-inter font-medium cursor-pointer" %>
    </div>
<% end %>

app/views/columns/edit.html.erb
<%= turbo_frame_tag :remote_modal do %>
  <dialog
    id="form_modal"
    aria-labelledby="modal_title"
    data-controller="modal">
        <header>
            <h2 id="modal_title" class="font-bold text-md">
                Edit column
            </h2>
            <form method="dialog">
                <button aria-label="close">
                    <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="2em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M6.793 6.793a1 1 0 0 1 1.414 0L12 10.586l3.793-3.793a1 1 0 1 1 1.414 1.414L13.414 12l3.793 3.793a1 1 0 0 1-1.414 1.414L12 13.414l-3.793 3.793a1 1 0 0 1-1.414-1.414L10.586 12L6.793 8.207a1 1 0 0 1 0-1.414" clip-rule="evenodd"/></svg>
                </button>
            </form>
        </header>
        <%= render "form", project: @project, column: @column %>
  </dialog>
<% end %>

app/views/columns/new.html.erb
<%
=begin%>
 <%= turbo_frame_tag dom_id(@column, dom_id(@project)) do %>
  <%= render "form", project: @project, column: @column %>
<% end %> 
<%
=end%>

<%= turbo_frame_tag :remote_modal do %>
  <dialog
    id="form_modal"
    aria-labelledby="modal_title"
    data-controller="modal">
        <header>
            <h2 id="modal_title" class="font-bold text-md">
                Add new column
            </h2>
            <form method="dialog">
                <button aria-label="close">
                    <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="2em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M6.793 6.793a1 1 0 0 1 1.414 0L12 10.586l3.793-3.793a1 1 0 1 1 1.414 1.414L13.414 12l3.793 3.793a1 1 0 0 1-1.414 1.414L12 13.414l-3.793 3.793a1 1 0 0 1-1.414-1.414L10.586 12L6.793 8.207a1 1 0 0 1 0-1.414" clip-rule="evenodd"/></svg>
                </button>
            </form>
        </header>
        <%= render "form", project: @project, column: @column %>
  </dialog>
<% end %>