config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show] do 
    collection do 
      get "attendance"
    end 
    resources :leafs, except: [:index, :show]
    resources :attendances, only: [:new, :create]
  end 
  resources :departments
  resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy] do 
    resources :columns, only: [:new, :create, :destroy, :edit, :update] do 
      patch "update_color"
      resources :cards, only: [:new, :create, :edit, :update, :destroy]
    end 
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "departments#index"
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :tenant 
  has_many :user_departments 
  has_many :users, through: :user_departments
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[show edit update destroy]
  def index
    @departments = Department.all
  end

  def new
  end

  def create
  end

  def show
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private 
  def set_department
    @department = Department.find(params[:id]) 
  end 
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<%= link_to department_path(department), class: "flex flex-col bg-gray-200 p-4 rounded-lg" do %>
    <h2><%= department.name %></h2>
    <p><%= department.user_departments.count %></p>
<% end %>

app/views/departments/_timeline.html.erb
<div class="w-full p-8">
<ol class="timeline w-full border-l-2 border-gray-400">
	<li class="w-full flex items-center gap-8 -ml-4 my-8">
		<img src="https://assets.codepen.io/285131/hat-man.png" class="w-8 h-8 rounded-full border-4 border-white" />
		<input type="text" placeholder="Add a comment..." class="w-full rounded-md"/>
	</li>
	<li class="w-full flex items-center gap-8 -ml-4 my-8">
		<span class="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white border-4 border-white">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20">
				<path fill="none" d="M0 0h24v24H0z" />
				<path fill="currentColor" d="M12.9 6.858l4.242 4.243L7.242 21H3v-4.243l9.9-9.9zm1.414-1.414l2.121-2.122a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414l-2.122 2.121-4.242-4.242z" />
			</svg>
		</span>
		<div class="w-full flex items-center space-x-2">
			<img src="https://assets.codepen.io/285131/winking-girl.png" class="w-8 h-8 rounded-full"/>
			<span class="w-full"><a href="#">Luna Bonifacio</a> has changed <a href="#">2 attributes</a> on <time datetime="21-01-2021">Jan 21, 2021</time></span>
		</div>
	</li>
    <li class="w-full flex items-center gap-8 -ml-4 my-8">
		<span class="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white border-4 border-white">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20">
				<path fill="none" d="M0 0h24v24H0z" />
				<path fill="currentColor" d="M12 13H4v-2h8V4l8 8-8 8z" />
			</svg>
		</span>
		<div class="w-full flex items-center space-x-2">
			<img src="https://assets.codepen.io/285131/hat-man.png" class="w-8 h-8 rounded-full"/>
			<span><a href="#">Yoan Almedia</a> moved <a href="#">Eric Lubin</a> to <a href="#">📚 Technical Test</a> on <time datetime="20-01-2021">Jan 20, 2021</time></span>
		</div>
	</li>
    <li class="w-full flex gap-8 -ml-4 my-8">
		<span class="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white border-4 border-white">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
				<path fill="none" d="M0 0h24v24H0z" />
				<path fill="currentColor" d="M6.455 19L2 22.5V4a1 1 0 0 1 1-1h18a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H6.455zM7 10v2h2v-2H7zm4 0v2h2v-2h-2zm4 0v2h2v-2h-2z" />
			</svg>
		</span>
        <div class="w-full flex flex-col space-y-2">
            <div class="w-full flex items-center space-x-2">
                <img src="https://assets.codepen.io/285131/hat-man.png" class="w-8 h-8 rounded-full"/>
                <span><a href="#">Yoan Almedia</a> commented on <time datetime="20-01-2021">Jan 20, 2021</time></span>
            </div>
            <div class="comment">
				<p>I've sent him the assignment we discussed recently, he is coming back to us this week. Regarding to our last call, I really enjoyed talking to him and so far he has the profile we are looking for. Can't wait to see his technical test, I'll keep you posted and we'll debrief it all together!😊</p>
				<button class="button">👏 2</button>
				<button class="button | square">
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
						<path fill="none" d="M0 0h24v24H0z" />
						<path fill="currentColor" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zM7 12a5 5 0 0 0 10 0h-2a3 3 0 0 1-6 0H7z" />
					</svg>
				</button>
			</div>
        </div>
	</li>
</ol>
</div>

app/views/departments/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Departments#create</h1>
  <p>Find me in app/views/departments/create.html.erb</p>
</div>

app/views/departments/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Departments#destroy</h1>
  <p>Find me in app/views/departments/destroy.html.erb</p>
</div>

app/views/departments/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Departments#edit</h1>
  <p>Find me in app/views/departments/edit.html.erb</p>
</div>

app/views/departments/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Departments#index</h1>
  <p>Find me in app/views/departments/index.html.erb</p>
  <div class="w-full mx-20 grid grid-cols-3 gap-4">
    <% @departments.each do |department| %>
      <%= render department %>
    <% end %>
  </div>
</div>

<%= render "timeline" %>

app/views/departments/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Departments#new</h1>
  <p>Find me in app/views/departments/new.html.erb</p>
</div>

app/views/departments/show.html.erb
<div>
  <h1 class="font-bold text-4xl"><%= @department.name %></h1>
  <p>Department Employees</p>
  <div class="flex flex-col gap-2 p-4">
    <% @department.user_departments.each do |u| %>
      <div class="">
        <%= link_to u.user.first_name, user_path(u.user), class: "" %></p>
        <%= link_to "add leave", new_user_leaf_path(u.user), class: "" %></p>
        <%= link_to "add attendance", new_user_attendance_path(u.user), class: "" %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/departments/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Departments#update</h1>
  <p>Find me in app/views/departments/update.html.erb</p>
</div>