config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show] do 
    collection do 
      get "attendance"
    end 
    resources :leafs, except: [:index, :show]
    resources :attendances, only: [:new, :create]
  end 
  resources :departments
  resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy] do 
    resources :columns, only: [:new, :create, :destroy, :edit, :update] do 
      patch "update_color"
      resources :cards, only: [:new, :create, :edit, :update, :destroy]
    end 
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "departments#index"
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :columns, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("projects", partial: "projects/project", locals: { project: @project})
          ]
        end 
      else
        format.html { render :new, status: :unprocessable_entity }
      end 
    end 
  end 

  def edit 
  end 

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(@project, partial: "projects/project", locals: { project: @project})
          ]
        end 
      else
        format.html { render :new, status: :unprocessable_entity }
      end 
    end 
  end

  def destroy
    @project.destroy 
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@project)
        ]
      end 
    end 
  end

  private

  def project_params
    params.require(:project).permit(:name, :description) 
  end 

  def set_project
    @project = Project.find(params[:id])
  end 
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, class:"flex flex-col") do |form| %>
    <div class="my-2">
        <%= form.text_field :name, class: "p-2 w-full border border-gray-200 rounded-md" %>
    </div>
    <div class="my-2">
        <%= form.text_area :description, class: "p-2 w-full border border-gray-200 rounded-md" %>
    </div>
    <div class="flex space-x-2 items-center">
        <%= form.submit "Save", data: { action: "click->modal#close" }, class: "py-1 px-4 border border-emerald-600 bg-emerald-600 text-sm sm:text-md text-white rounded-md font-inter font-medium cursor-pointer" %>
        <%= form.button "Close", value: nil, formmethod: :dialog, class: "py-1 px-4 border border-emerald-600 text-emerald-600 text-sm sm:text-md rounded-md font-inter font-medium cursor-pointer" %>
    </div>
<% end %>

app/views/projects/_project.html.erb
<%= turbo_frame_tag dom_id(project), class: "p-4 bg-emerald-200" do %>
    <p class="text-emarald-600 font-bold uppercase text-md"><%= project.name %></p>
    <p class="text-emarald-400 text-sm"><%= project.description %></p>
    <div class="flex items-center space-x-2">
        <%= link_to "View", project_path(project), data: { turbo: false }, class: "block" %>
        <%= link_to "Edit project", edit_project_path(project), data: { turbo_frame: :remote_modal }, class: "cursor-pointer font-medium text-black text-md py-1" %>
        <%= button_to "Destroy", project_path(project), method: :delete, class: "py-1 px-4 border border-red-600 bg-red-600 text-sm sm:text-md text-white rounded-md font-inter font-medium cursor-pointer" %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<%= turbo_frame_tag :remote_modal do %>
  <dialog
    id="form_modal"
    aria-labelledby="modal_title"
    data-controller="modal">
        <header>
            <h2 id="modal_title" class="font-bold text-md">
                Edit project
            </h2>
            <form method="dialog">
                <button aria-label="close">
                    <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="2em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M6.793 6.793a1 1 0 0 1 1.414 0L12 10.586l3.793-3.793a1 1 0 1 1 1.414 1.414L13.414 12l3.793 3.793a1 1 0 0 1-1.414 1.414L12 13.414l-3.793 3.793a1 1 0 0 1-1.414-1.414L10.586 12L6.793 8.207a1 1 0 0 1 0-1.414" clip-rule="evenodd"/></svg>
                </button>
            </form>
        </header>
        <%= render "form", project: @project %>
  </dialog>
<% end %>

app/views/projects/index.html.erb
<div class="flex flex-col p-4">
  <div class="flex justify-between">
    <div>
      <h1 class="font-bold text-4xl">Projects#index</h1>
      <p>Find me in app/views/projects/index.html.erb</p>
    </div>
    <%= link_to "Add new", new_project_path, data: { turbo_frame: :remote_modal }, class: "bg-emerald-600 text-white rounded-md py-1 px-2 self-start" %>
  </div> 

  <%= turbo_frame_tag "projects", class: "w-full grid grid-cols-3 gap-4" do %>
    <% @projects.each do |project| %>
      <%= render project %>
    <% end %>
  <% end %>
</div>

app/views/projects/new.html.erb
<%= turbo_frame_tag :remote_modal do %>
  <dialog
    id="form_modal"
    aria-labelledby="modal_title"
    data-controller="modal">
        <header>
            <h2 id="modal_title" class="font-bold text-md">
                Add new project
            </h2>
            <form method="dialog">
                <button aria-label="close">
                    <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="2em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M6.793 6.793a1 1 0 0 1 1.414 0L12 10.586l3.793-3.793a1 1 0 1 1 1.414 1.414L13.414 12l3.793 3.793a1 1 0 0 1-1.414 1.414L12 13.414l-3.793 3.793a1 1 0 0 1-1.414-1.414L10.586 12L6.793 8.207a1 1 0 0 1 0-1.414" clip-rule="evenodd"/></svg>
                </button>
            </form>
        </header>
        <%= render "form", project: @project %>
  </dialog>
<% end %>

app/views/projects/show.html.erb
<div class="p-4">
  <h1 class="font-bold text-4xl"><%= @project.name %></h1>
  
  <div class="w-full bg-yellow-50 py-4 px-8 border border-gray-200 flex flex-row gap-2">
    <%= turbo_frame_tag dom_id(@project), class: "flex flex-row gap-4 overflow-x-auto" do %>
      <% @project.columns.ordered.each do |column| %>
        <%= render column %>
      <% end %>
    <% end %>
    <%= link_to new_project_column_path(@project), data: { turbo_frame: :remote_modal}, class: "bg-emerald-600 text-white rounded-full p-1 self-start w-8 h-8 flex items-center justify-center" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="2em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6z"/></svg>
    <% end %>
  </div>
</div>