config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show] do 
    collection do 
      get "attendance"
    end 
    resources :leafs, except: [:index, :show]
    resources :attendances, only: [:new, :create]
  end 
  resources :departments
  resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy] do 
    resources :columns, only: [:new, :create, :destroy, :edit, :update] do 
      patch "update_color"
      resources :cards, only: [:new, :create, :edit, :update, :destroy]
    end 
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "departments#index"
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :column
  belongs_to :user

  scope :ordered, -> { order(created_at: :desc)}
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    before_action :set_column, only: %i[new create edit update destroy]
    def new
        @card = Card.new
    end 

    def create
        @card = @column.cards.build(card_params)
        @card.user_id = "3b51f9af-3230-408a-9ac3-835592f1bdfe"
        respond_to do |format|
            if @card.save
                format.turbo_stream do 
                    render turbo_stream: [
                        # turbo_stream.prepend("#{@column.id}_cards", partial: "cards/card", locals: { card: @card }),
                        # turbo_stream.update("card_count_#{@column.id}", "(#{@column.cards.count})")
                        turbo_stream.replace(@column, partial: "columns/column", locals: { column: @column })
                    ]
                end
            end
        end
    end

    def edit
        @card = Card.find(params[:id])
    end
    
    def update
        @card = Card.find(params[:id])
        respond_to do |format|
            if @card.update(card_params)
                format.turbo_stream do
                    render turbo_stream: [
                        turbo_stream.replace(@card, partial: "cards/card", locals: { card: @card })
                    ]
                end
            end
        end 
    end 
    
    def destroy
        @card = Card.find(params[:id])
        @card.destroy
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.remove(@card), 
              turbo_stream.update("card_count_#{@column.id}", "(#{@column.cards.count})")
            ]
          end 
        end 
    end

    private 

    def card_params
        params.require(:card).permit(:title, :description)
    end 

    def set_column
        @column = Column.find(params[:column_id])
    end 
end

app/views/cards/_card.html.erb
<%= turbo_frame_tag dom_id(card), class: "p-2 bg-gray-50 shadow-md border border-gray-200 rounded-md flex flex-col" do %>
    <div class="grid grid-cols-[1fr,auto] gap-2">
        <div class="w-full truncate">
            <p class="font-bold text-md"><%= card.title %></p>
            <p class="font-normal text-base text-gray-600"><%= card.description %></p>
        </div>
        <div class="h-8 w-8 rounded-full text-gray-600 flex items-center justify-center cursor-pointer" data-popover-target="<%= card.id %>_popover_click" data-popover-trigger="click" data-popover-placement="bottom">
            <svg xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" viewBox="0 0 256 256"><path fill="currentColor" d="M144 128a16 16 0 1 1-16-16a16 16 0 0 1 16 16m-84-16a16 16 0 1 0 16 16a16 16 0 0 0-16-16m136 0a16 16 0 1 0 16 16a16 16 0 0 0-16-16"/></svg>
        </div>
        <div class="absolute z-10 invisible inline-block w-64 text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 p-4" data-popover id="<%= card.id %>_popover_click" role="tooltip">
            <div class="flex flex-col">
                <p class="font-bold text-black text-md"><%= card.title %></p>
                <p class="text-gray-600 text-base"><%= card.description %></p>
            </div>
            <hr class="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700">
            <%= link_to "Edit card", edit_project_column_card_path(card.column.project, card.column, card), data: { turbo_frame: :remote_modal }, class: "cursor-pointer font-medium text-black text-md py-1" %>
            <hr class="h-px my-2 bg-gray-200 border-0 dark:bg-gray-700">
            <%= button_to "Destroy", project_column_card_path(card.column.project, card.column, card), method: :delete, class: "py-1 px-4 border border-red-600 bg-red-600 text-sm sm:text-md text-white rounded-md font-inter font-medium cursor-pointer" %>
            <div data-popper-arrow></div>
        </div>
    </div>
    <div class="mt-2">
        <p class="text-gray-400 text-sm">By <%= card.user.full_name %></p>
    </div>
<% end %>

app/views/cards/_form.html.erb
<%= form_with(model: [column.project, column, card], class: "flex flex-col space-y-2") do |form|%>
    <%= form.text_field :title, placeholder: "Title", class: "p-2 w-full border border-gray-200 rounded-md" %>
    <%= form.text_area :description, placeholder: "Description", class: "p-2 w-full border border-gray-200 rounded-md" %>
    <div class="flex space-x-2 items-center">
        <%= form.submit "Save", data: { action: "click->modal#close" }, class: "py-1 px-4 border border-emerald-600 bg-emerald-600 text-sm sm:text-md text-white rounded-md font-inter font-medium cursor-pointer" %>
        <%= form.button "Close", value: nil, formmethod: :dialog, class: "py-1 px-4 border border-emerald-600 text-emerald-600 text-sm sm:text-md rounded-md font-inter font-medium cursor-pointer" %>
    </div>
<% end %>

app/views/cards/edit.html.erb
<%= turbo_frame_tag :remote_modal do %>
  <dialog
    id="form_modal"
    aria-labelledby="modal_title"
    data-controller="modal">
        <header>
            <h2 id="modal_title" class="font-bold text-md">
                Edit card
            </h2>
            <form method="dialog">
                <button aria-label="close">
                    <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="2em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M6.793 6.793a1 1 0 0 1 1.414 0L12 10.586l3.793-3.793a1 1 0 1 1 1.414 1.414L13.414 12l3.793 3.793a1 1 0 0 1-1.414 1.414L12 13.414l-3.793 3.793a1 1 0 0 1-1.414-1.414L10.586 12L6.793 8.207a1 1 0 0 1 0-1.414" clip-rule="evenodd"/></svg>
                </button>
            </form>
        </header>
        <%= render "form", column: @column, card: @card %>
  </dialog>
<% end %>

app/views/cards/new.html.erb
<%
=begin%>
 <%= turbo_frame_tag :remote_modal do %>
  <dialog
    id="form_modal"
    aria-labelledby="modal_title"
    data-controller="modal">
        <header>
            <h2 id="modal_title" class="font-bold text-md">
                Add new card
            </h2>
            <form method="dialog">
                <button aria-label="close">
                    <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="2em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M6.793 6.793a1 1 0 0 1 1.414 0L12 10.586l3.793-3.793a1 1 0 1 1 1.414 1.414L13.414 12l3.793 3.793a1 1 0 0 1-1.414 1.414L12 13.414l-3.793 3.793a1 1 0 0 1-1.414-1.414L10.586 12L6.793 8.207a1 1 0 0 1 0-1.414" clip-rule="evenodd"/></svg>
                </button>
            </form>
        </header>
        <%= render "form", column: @column, card: @card %>
  </dialog>
<% end %> 
<%
=end%>
<%= turbo_frame_tag @card do %>
    <%= render "form", column: @column, card: @card %>
<% end %>